USE [PettyCashDb]
GO

-- ==============================================================================
-- SEED GEOGRAPHIC DATA SCRIPT (Countries, Regions, Districts)
-- Sourced from RealEstateDatabase
-- ==============================================================================

-- 1. Temporarily disable FK constraints to ensure smooth, dependency-safe insertion
ALTER TABLE [dbo].[Districts] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Regions] NOCHECK CONSTRAINT ALL;
GO

-- ==============================================================================
-- 2. INSERT COUNTRIES (1 - 248)
-- ==============================================================================
PRINT 'Inserting Countries...';
SET IDENTITY_INSERT [dbo].[Countries] ON;
GO

INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (1, N'ABW', N'Aruba', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (2, N'AFG', N'Afghanistan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (3, N'AGO', N'Angola', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (4, N'AIA', N'Anguilla', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (5, N'ALA', N'Åland Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (6, N'ALB', N'Albania', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (7, N'AND', N'Andorra', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (8, N'ANT', N'Netherlands Antilles', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (9, N'ARE', N'United Arab Emirates', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (10, N'ARG', N'Argentina', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (11, N'ARM', N'Armenia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (12, N'ASM', N'American Samoa', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (13, N'ATA', N'Antarctica', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (14, N'ATF', N'French Southern Territories', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (15, N'ATG', N'Antigua and Barbuda', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (16, N'AUS', N'Australia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (17, N'AUT', N'Austria', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (18, N'AZE', N'Azerbaijan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (19, N'BDI', N'Burundi', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (20, N'BEL', N'Belgium', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (21, N'BEN', N'Benin', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (22, N'BFA', N'Burkina Faso', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (23, N'BGD', N'Bangladesh', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (24, N'BGR', N'Bulgaria', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (25, N'BHR', N'Bahrain', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (26, N'BHS', N'Bahamas', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (27, N'BIH', N'Bosnia and Herzegovina', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (28, N'BLM', N'Saint Barthélemy', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (29, N'BLR', N'Belarus', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (30, N'BLZ', N'Belize', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (31, N'BMU', N'Bermuda', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (32, N'BOL', N'Bolivia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (33, N'BRA', N'Brazil', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (34, N'BRB', N'Barbados', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (35, N'BRN', N'Brunei Darussalam', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (36, N'BTN', N'Bhutan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (37, N'BVT', N'Bouvet Island', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (38, N'BWA', N'Botswana', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (39, N'CAF', N'Central African Republic', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (40, N'CAN', N'Canada', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (41, N'CCK', N'Cocos (Keeling) Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (42, N'CHE', N'Switzerland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (43, N'CHL', N'Chile', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (44, N'CHN', N'China', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (45, N'CIV', N'Côte d''Ivoire', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (46, N'CMR', N'Cameroon', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (47, N'COD', N'Congo, the Democratic Republic of the', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (48, N'COG', N'Congo', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (49, N'COK', N'Cook Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (50, N'COL', N'Colombia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (51, N'COM', N'Comoros', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (52, N'CPV', N'Cape Verde', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (53, N'CRI', N'Costa Rica', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (54, N'CUB', N'Cuba', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (55, N'CXR', N'Christmas Island', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (56, N'CYM', N'Cayman Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (57, N'CYP', N'Cyprus', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (58, N'CZE', N'Czech Republic', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (59, N'DEU', N'Germany', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (60, N'DJI', N'Djibouti', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (61, N'DMA', N'Dominica', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (62, N'DNK', N'Denmark', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (63, N'DOM', N'Dominican Republic', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (64, N'DZA', N'Algeria', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (65, N'ECU', N'Ecuador', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (66, N'EGY', N'Egypt', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (67, N'ERI', N'Eritrea', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (68, N'ESH', N'Western Sahara', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (69, N'ESP', N'Spain', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (70, N'EST', N'Estonia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (71, N'ETH', N'Ethiopia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (72, N'FIN', N'Finland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (73, N'FJI', N'Fiji', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (74, N'FLK', N'Falkland Islands (Malvinas)', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (75, N'FRA', N'France', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (76, N'FRO', N'Faroe Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (77, N'FSM', N'Micronesia, Federated States of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (78, N'GAB', N'Gabon', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (79, N'GBR', N'England', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (80, N'GEO', N'Georgia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (81, N'GGY', N'Guernsey', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (82, N'GHA', N'Ghana', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (83, N'GIN', N'Guinea', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (84, N'GIB', N'Gibraltar', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (85, N'GLP', N'Guadeloupe', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (86, N'GMB', N'Gambia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (87, N'GNB', N'Guinea-Bissau', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (88, N'GNQ', N'Equatorial Guinea', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (89, N'GRC', N'Greece', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (90, N'GRD', N'Grenada', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (91, N'GRL', N'Greenland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (92, N'GTM', N'Guatemala', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (93, N'GUF', N'French Guiana', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (94, N'GUM', N'Guam', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (95, N'GUY', N'Guyana', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (96, N'HKG', N'Hong Kong', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (97, N'HMD', N'Heard Island and McDonald Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (98, N'HND', N'Honduras', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (99, N'HRV', N'Croatia', 0)
GO
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (100, N'HTI', N'Haiti', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (101, N'HUN', N'Hungary', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (102, N'IDN', N'Indonesia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (103, N'IMN', N'Isle of Man', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (104, N'IND', N'India', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (105, N'IOT', N'British Indian Ocean Territory', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (106, N'IRL', N'Ireland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (107, N'IRN', N'Iran, Islamic Republic of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (108, N'IRQ', N'Iraq', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (109, N'ISL', N'Iceland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (110, N'ISR', N'Israel', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (111, N'ITA', N'Italy', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (112, N'JAM', N'Jamaica', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (113, N'JEY', N'Jersey', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (114, N'JOR', N'Jordan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (115, N'JPN', N'Japan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (116, N'KAZ', N'Kazakhstan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (117, N'KEN', N'Kenya', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (118, N'KGZ', N'Kyrgyzstan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (119, N'KHM', N'Cambodia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (120, N'KIR', N'Kiribati', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (121, N'KNA', N'Saint Kitts and Nevis', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (122, N'KOR', N'Korea, Republic of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (123, N'KWT', N'Kuwait', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (124, N'LAO', N'Lao People''s Democratic Republic', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (125, N'LBN', N'Lebanon', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (126, N'LBR', N'Liberia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (127, N'LBY', N'Libyan Arab Jamahiriya', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (128, N'LCA', N'Saint Lucia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (129, N'LIE', N'Liechtenstein', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (130, N'LKA', N'Sri Lanka', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (131, N'LSO', N'Lesotho', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (132, N'LTU', N'Lithuania', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (133, N'LUX', N'Luxembourg', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (134, N'LVA', N'Latvia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (135, N'MAC', N'Macao', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (136, N'MAF', N'Saint Martin (French part)', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (137, N'MAR', N'Morocco', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (138, N'MCO', N'Monaco', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (139, N'MDA', N'Moldova', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (140, N'MDG', N'Madagascar', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (141, N'MDV', N'Maldives', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (142, N'MEX', N'Mexico', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (143, N'MHL', N'Marshall Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (144, N'MKD', N'Macedonia, the former Yugoslav Republic of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (145, N'MLI', N'Mali', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (146, N'MLT', N'Malta', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (147, N'MMR', N'Myanmar', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (148, N'MNE', N'Montenegro', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (149, N'MNG', N'Mongolia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (150, N'MNP', N'Northern Mariana Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (151, N'MOZ', N'Mozambique', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (152, N'MRT', N'Mauritania', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (153, N'MSR', N'Montserrat', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (154, N'MTQ', N'Martinique', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (155, N'MUS', N'Mauritius', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (156, N'MWI', N'Malawi', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (157, N'MYS', N'Malaysia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (158, N'MYT', N'Mayotte', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (159, N'NAM', N'Namibia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (160, N'NCL', N'New Caledonia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (161, N'NER', N'Niger', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (162, N'NFK', N'Norfolk Island', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (163, N'NGA', N'Nigeria', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (164, N'NIC', N'Nicaragua', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (165, N'NOR', N'Norway', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (166, N'NIU', N'Niue', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (167, N'NLD', N'Netherlands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (168, N'NPL', N'Nepal', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (169, N'NRU', N'Nauru', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (170, N'NZL', N'New Zealand', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (171, N'OMN', N'Oman', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (172, N'PAK', N'Pakistan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (173, N'PAN', N'Panama', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (174, N'PCN', N'Pitcairn', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (175, N'PER', N'Peru', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (176, N'PHL', N'Philippines', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (177, N'PLW', N'Palau', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (178, N'PNG', N'Papua New Guinea', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (179, N'POL', N'Poland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (180, N'PRI', N'Puerto Rico', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (181, N'PRK', N'Korea, Democratic People''s Republic of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (182, N'PRT', N'Portugal', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (183, N'PRY', N'Paraguay', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (184, N'PSE', N'Palestinian Territory, Occupied', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (185, N'PYF', N'French Polynesia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (186, N'QAT', N'Qatar', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (187, N'REU', N'Réunion', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (188, N'ROU', N'Romania', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (189, N'RUS', N'Russian Federation', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (190, N'RWA', N'Rwanda', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (191, N'SAU', N'Saudi Arabia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (192, N'SDN', N'Sudan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (193, N'SEN', N'Senegal', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (194, N'SGP', N'Singapore', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (195, N'SGS', N'South Georgia and the South Sandwich Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (196, N'SHN', N'Saint Helena', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (197, N'SJM', N'Svalbard and Jan Mayen', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (198, N'SLB', N'Solomon Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (199, N'SLE', N'Sierra Leone', 0)
GO
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (200, N'SLV', N'El Salvador', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (201, N'SMR', N'San Marino', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (202, N'SOM', N'Somalia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (203, N'SPM', N'Saint Pierre and Miquelon', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (204, N'SRB', N'Serbia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (205, N'STP', N'Sao Tome and Principe', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (206, N'SUR', N'Suriname', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (207, N'SVK', N'Slovakia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (208, N'SVN', N'Slovenia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (209, N'SWE', N'Sweden', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (210, N'SWZ', N'Swaziland', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (211, N'SYC', N'Seychelles', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (212, N'SYR', N'Syrian Arab Republic', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (213, N'TCA', N'Turks and Caicos Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (214, N'TCD', N'Chad', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (215, N'TGO', N'Togo', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (216, N'THA', N'Thailand', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (217, N'TJK', N'Tajikistan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (218, N'TKL', N'Tokelau', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (219, N'TKM', N'Turkmenistan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (220, N'TLS', N'Timor-Leste', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (221, N'TON', N'Tonga', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (222, N'TTO', N'Trinidad and Tobago', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (223, N'TUN', N'Tunisia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (224, N'TUR', N'Turkey', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (225, N'TUV', N'Tuvalu', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (226, N'TWN', N'Taiwan, Province of China', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (227, N'TZA', N'Tanzania, United Republic of', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (228, N'UGA', N'Uganda', 1)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (229, N'UKR', N'Ukraine', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (230, N'UMI', N'United States Minor Outlying Islands', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (231, N'URY', N'Uruguay', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (232, N'USA', N'United States', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (233, N'UZB', N'Uzbekistan', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (234, N'VAT', N'Holy See (Vatican City State)', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (235, N'VCT', N'Saint Vincent and the Grenadines', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (236, N'VEN', N'Venezuela', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (237, N'VGB', N'Virgin Islands, British', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (238, N'VIR', N'Virgin Islands, U.S.', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (239, N'VNM', N'Viet Nam', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (240, N'VUT', N'Vanuatu', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (241, N'WLF', N'Wallis and Futuna', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (242, N'WSM', N'Samoa', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (243, N'YEM', N'Yemen', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (244, N'ZAF', N'South Africa', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (245, N'ZMB', N'Zambia', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (246, N'ZWE', N'Zimbabwe', 0)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (247, N'RSS', N'South Sudan', 1)
INSERT [dbo].[Countries] ([ID], [Code], [CountryName], [Enabled]) VALUES (248, N'Choose', N'Choose Country', 1)
GO

SET IDENTITY_INSERT [dbo].[Countries] OFF;
GO

-- ==============================================================================
-- 3. INSERT REGIONS (1 - 5)
-- Note: Inserted BEFORE Districts so FK_Districts_Regions is fully satisfied!
-- ==============================================================================
PRINT 'Inserting Regions...';
SET IDENTITY_INSERT [dbo].[Regions] ON;
GO

INSERT [dbo].[Regions] ([RegionID], [RegionName], [Country], [State]) VALUES (1, N'Central', 228, NULL)
INSERT [dbo].[Regions] ([RegionID], [RegionName], [Country], [State]) VALUES (2, N'Eastern', 228, NULL)
INSERT [dbo].[Regions] ([RegionID], [RegionName], [Country], [State]) VALUES (3, N'Nothern', 228, NULL)
INSERT [dbo].[Regions] ([RegionID], [RegionName], [Country], [State]) VALUES (4, N'Western', 228, NULL)
INSERT [dbo].[Regions] ([RegionID], [RegionName], [Country], [State]) VALUES (5, N'Uganda', 228, NULL)
GO

SET IDENTITY_INSERT [dbo].[Regions] OFF;
GO

-- ==============================================================================
-- 4. INSERT DISTRICTS (13 - 152)
-- ==============================================================================
PRINT 'Inserting Districts...';
SET IDENTITY_INSERT [dbo].[Districts] ON;
GO

INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (13, N'Abim', 228, NULL, 3, N'Abim', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (14, N'Adjumani', 228, NULL, 3, N'Adjumani', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (15, N'Amolatar', 228, NULL, 3, N'Amolatar', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (16, N'Amuria', 228, NULL, 2, N'Amuria', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (17, N'Apac', 228, NULL, 3, N'Apac', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (18, N'Arua', 228, NULL, 3, N'Arua', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (19, N'Budaka', 228, NULL, 2, N'Budaka', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (20, N'Bugiri', 228, NULL, 2, N'Bugiri', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (21, N'Bukwa', 228, NULL, 2, N'Bukwa', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (22, N'Buliisa', 228, NULL, 4, N'Bulisa', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (23, N'Bundibugyo', 228, NULL, 4, N'Bundibugyo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (24, N'Busheenyi', 228, NULL, 4, N'Bushenyi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (25, N'Busia', 228, NULL, 2, N'Busia', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (26, N'Busiki', 228, NULL, 2, N'Busiki', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (27, N'Butaleeja', 228, NULL, 2, N'Butaleja', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (28, N'Dokolo', 228, NULL, 3, N'Dokolo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (29, N'Gulu', 228, NULL, 3, N'Gulu', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (30, N'Hoima', 228, NULL, 4, N'Hoima', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (31, N'Ibanda', 228, NULL, 4, N'Ibanda', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (32, N'Iganga', 228, NULL, 2, N'Iganga', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (33, N'Jinja', 228, NULL, 2, N'Jinja', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (34, N'Kaabong', 228, NULL, 3, N'Kaabong', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (35, N'Kabaale', 228, NULL, 4, N'Kabale', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (36, N'Kabarole', 228, NULL, 4, N'Kabarole', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (37, N'Kaberamaido', 228, NULL, 2, N'Kaberamaido', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (38, N'Kabingo', 228, NULL, 4, N'Kabingo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (39, N'Kalangala', 228, NULL, 1, N'Kalangala', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (40, N'Kaliro', 228, NULL, 2, N'Kaliro', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (41, N'Kampala', 228, NULL, 1, N'Kampala', 3)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (42, N'Kamuli', 228, NULL, 2, N'Kamuli', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (43, N'Kamwenge', 228, NULL, 4, N'Kamwenge', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (44, N'Kanungu', 228, NULL, 4, N'Kanungu', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (45, N'Kapchorwa', 228, NULL, 2, N'Kapchorwa', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (46, N'Kaseese', 228, NULL, 4, N'Kasese', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (47, N'Katakwi', 228, NULL, 2, N'Katakwi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (48, N'Kayunga', 228, NULL, 1, N'Kayunga', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (49, N'Kibaale', 228, NULL, 4, N'Kibale', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (50, N'Kiboga', 228, NULL, 1, N'Kiboga', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (51, N'Kilak', 228, NULL, 3, N'Kilak', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (52, N'Kiruhura', 228, NULL, 4, N'Kiruhura', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (53, N'Kisoro', 228, NULL, 4, N'Kisoro', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (54, N'Kitgum', 228, NULL, 3, N'Kitgum', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (55, N'Koboko', 228, NULL, 3, N'Koboko', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (56, N'Kotido', 228, NULL, 3, N'Kotido', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (57, N'Kumi', 228, NULL, 2, N'Kumi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (58, N'Kyenjojo', 228, NULL, 4, N'Kyenjojo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (59, N'Lira', 228, NULL, 3, N'Lira', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (60, N'Luweero', 228, NULL, 1, N'Luwero', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (61, N'Manafwa', 228, NULL, 2, N'Manafwa', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (62, N'Maracha', 228, NULL, 3, N'Maracha', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (63, N'Masaka', 228, NULL, 1, N'Masaka', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (64, N'Masindi', 228, NULL, 4, N'Masindi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (65, N'Mayuge', 228, NULL, 2, N'Mayuge', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (66, N'Mbaale', 228, NULL, 2, N'Mbale', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (67, N'Mbarara', 228, NULL, 4, N'Mbarara', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (68, N'Mityana', 228, NULL, 1, N'Mityana', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (69, N'Moroto', 228, NULL, 3, N'Moroto', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (70, N'Moyo', 228, NULL, 3, N'Moyo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (71, N'Mpigi', 228, NULL, 1, N'Mpigi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (72, N'Mubende', 228, NULL, 1, N'Mubende', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (73, N'Mukono', 228, NULL, 1, N'Mukono', 1)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (74, N'Nakapiripirit', 228, NULL, 3, N'Nakapiripirit', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (75, N'Nakaseke', 228, NULL, 1, N'Nakaseke', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (76, N'Nakasongola', 228, NULL, 1, N'Nakasongola', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (77, N'Nebbi', 228, NULL, 3, N'Nebbi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (78, N'Ntungamo', 228, NULL, 4, N'Ntungamo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (79, N'Oyam', 228, NULL, 3, N'Oyam', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (80, N'Pader', 228, NULL, 3, N'Pader', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (81, N'Pallisa', 228, NULL, 2, N'Pallisa', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (82, N'Rakai', 228, NULL, 1, N'Rakai', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (83, N'Rukungiri', 228, NULL, 4, N'Rukungiri', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (84, N'Sembabule', 228, NULL, 1, N'Sembabule', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (85, N'Sironko', 228, NULL, 2, N'Sironko', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (86, N'Soroti', 228, NULL, 2, N'Soroti', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (87, N'Tororo', 228, NULL, 2, N'Tororo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (88, N'Wakiso', 228, NULL, 1, N'Wakiso', 2)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (89, N'Yumbe', 228, NULL, 3, N'Yumbe', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (90, N'Nakuru', 117, NULL, 5, N'Nakuru', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (91, N'Mulanga', 227, NULL, 5, N'Mulanga', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (92, N'Kilimanjaro', 227, NULL, 5, N'Kilimanjaro', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (93, N'Juba', 247, NULL, 5, N'Juba', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (94, N'Bugesera', 190, NULL, 5, N'Bugesera', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (95, N'Gatsibo', 190, NULL, 5, N'Gatsibo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (96, N'Kayonza', 190, NULL, 5, N'Kayonza', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (97, N'Kirehe', 190, NULL, 5, N'Kirehe', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (98, N'Ngoma', 190, NULL, 5, N'Ngoma', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (99, N'Nyagatare', 190, NULL, 5, N'Nyagatare', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (100, N'Rwamagana', 190, NULL, 5, N'Rwamagana', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (101, N'Gasabo', 190, NULL, 5, N'Gasabo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (102, N'Kicukiro', 190, NULL, 5, N'Kicukiro', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (103, N'Nyarugenge', 190, NULL, 5, N'Nyarugenge', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (104, N'Burera', 190, NULL, 5, N'Burera', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (105, N'Gakenke', 190, NULL, 5, N'Gakenke', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (106, N'Gicumbi', 190, NULL, 5, N'Gicumbi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (107, N'Musanze', 190, NULL, 5, N'Musanze', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (108, N'Rulindo', 190, NULL, 5, N'Rulindo', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (109, N'Gisagara', 190, NULL, 5, N'Gisagara', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (110, N'Huye', 190, NULL, 5, N'Huye', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (111, N'Kamonyi', 190, NULL, 5, N'Kamonyi', 0)
GO
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (112, N'Muhanga', 190, NULL, 5, N'Muhanga', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (113, N'Nyamagabe', 190, NULL, 5, N'Nyamagabe', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (114, N'Nyanza', 190, NULL, 5, N'Nyanza', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (115, N'Nyaruguru', 190, NULL, 5, N'Nyaruguru', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (116, N'Ruhango', 190, NULL, 5, N'Ruhango', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (117, N'Karongi', 190, NULL, 5, N'Karongi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (118, N'Ngororero', 190, NULL, 5, N'Ngororero', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (119, N'Nyabihu', 190, NULL, 5, N'Nyabihu', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (120, N'Nyamasheke', 190, NULL, 5, N'Nyamasheke', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (121, N'Rubavu', 190, NULL, 5, N'Rubavu', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (122, N'Rusizi', 190, NULL, 5, N'Rusizi', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (123, N'Rutsiro', 190, NULL, 5, N'Rutsiro', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (124, N'  Select', 228, NULL, 1, N'0', 4)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (125, N'International', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (126, N'Butambala', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (127, N'Kalungu', 228, NULL, 1, N'Kalungu', 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (128, N'Buyikwe', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (129, N'Gomba', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (130, N'Luuka', 228, NULL, 2, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (131, N'Amuru', 228, NULL, 3, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (132, N'Nwoya', 228, NULL, 3, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (133, N'Bulambuli', 228, NULL, 2, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (134, N'Bukomansimbi', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (135, N'Kyankwazi', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (136, N'Kyotera', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (137, N'Lyantonde', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (138, N'Buvuma', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (139, N'Agago', 228, NULL, 3, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (140, N'Lwengo', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (141, N'Kasanda', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (142, N'Kibuube', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (143, N'Kiryandongo', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (144, N'Nabilatuk', 228, NULL, 3, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (145, N'Kyegegwa', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (146, N'Isingilo', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (147, N'Kakumiro', 228, NULL, 1, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (148, N'Kazo', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (149, N'Kibingo', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (150, N'Namutumba', 228, NULL, 2, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (151, N'Rwampara', 228, NULL, 4, NULL, 0)
INSERT [dbo].[Districts] ([DistrictID], [DistrictName], [Country], [State], [Region], [TempDistrict], [Position]) VALUES (152, N'Butebo', 228, NULL, 2, NULL, 0)
GO

SET IDENTITY_INSERT [dbo].[Districts] OFF;
GO

-- ==============================================================================
-- 5. RE-ENABLE AND VERIFY ALL FOREIGN KEY CONSTRAINTS
-- ==============================================================================
PRINT 'Re-enabling and validating foreign key constraints...';
ALTER TABLE [dbo].[Regions] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Districts] WITH CHECK CHECK CONSTRAINT ALL;
GO

PRINT 'Geographic data seeded successfully!';
GO
